#!/bin/bash


for I in {nodels compd}
do
touch /etc/nagiosi/nodes/compute-nodes/compd$I.cfg
cat << EOF > /etc/nagios/nodes/compute-nodes/compd$I.cfg

define host{
	use		compute-node
	host_name	compd$I
	alias		compd$I
	address		compd$I
	hostgroups	compute-d
}
EOF
done
