#!/bin/bash


for I in {nodels compb}
do
touch /etc/nagios/nodes/compute-nodes/mocompb$I.cfg
cat << EOF > /etc/nagios/nodes/compute-nodes/mocompb$I.cfg

define host{
	use		compute-node
	host_name	mocompb$I
	alias		mocompb$I
	address		mocompb$I
	hostgroups	compute-b
}
EOF
done
