#!/bin/bash


for I in {nodels compb}
do
touch /etc/nagios/nodes/compute-nodes/compb$I.cfg
cat << EOF > /etc/nagios/nodes/compute-nodes/compb$I.cfg

define host{
	use		compute-node
	hostname	compb$I
	alias		compb$I
	address		compb$I
	hostgroups	compute-b
}
EOF
done
