#!/bin/bash


for I in {nodels compc}
do
touch /etc/nagios/nodes/compute-nodes/compc$I.cfg
cat << EOF > /etc/nagios/nodes/compute-nodes/compc$I.cfg

define host{
	use		compute-node
	hostname	compc$I
	alias		compc$I
	address		compc$I
	hostgroups	compute-c
}
EOF
done
